version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dumi
    versions:
    - 1.1.13
    - 1.1.14
    - 1.1.15
  - dependency-name: dumi-theme-default
    versions:
    - 1.0.5
